In [67]:
import pandas as pd
import numpy as np

In [68]:
df = pd.read_csv(r'unclean_listings.csv')
df.shape

(25960, 14)

In [69]:
df = df[df['header'].str.contains('Rover') == False]
df = df[df['header'].str.contains('Romeo') == False]
df = df[df['header'].str.contains('Martin') == False]
df.head()

,vin,header,trim,price,location,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain,engine,Unnamed: 13
0,1FTEW1EP5LKF18954,2020 Ford F-150,XL SuperCrew 5.5' Box 4WD,"$25,699","Littleton, CO","76,799 miles",Exterior: Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,2.7L V-6 Gas Turbocharged,NaN
1,1N4AL3AP4FC588068,2015 Nissan Altima,2.5 S,"$10,250","Austin, TX","114,701 miles",Exterior: Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,2.5L Inline-4 Gas,NaN
2,1FMSK8DH6LGB88354,2020 Ford Explorer,XLT 4WD,"$22,988","Seekonk, MA","141,184 miles",Exterior: Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD,2.3L Inline-4 Gas Turbocharged,NaN
3,1N4AL3AP7FC185069,2015 Nissan Altima,2.5 S,"$8,999","San Diego, CA","108,333 miles",Exterior: Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,2.5L Inline-4 Gas,NaN
4,1FTEW1EP8LKF49809,2020 Ford F-150,Lariat SuperCrew 5.5' Box 4WD,"$43,990$42,772","Milwaukee, WI","48,717 miles",Exterior: Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,2.7L V-6 Gas Turbocharged,NaN

In [70]:
new_cols = df['header'].str.split(pat=' ', n=3, expand=True)
df['year'] = new_cols[0]
df['make'] = new_cols[1]
df['model'] = new_cols[2]
df['year'] = df['year'].str.replace('Sponsored','')
df = df[df['year'] != '']
df = df[['vin', 'year', 'make', 'model', 'trim', 'price', 'location', 'mileage', 'exterior_color', 'interior_color', 'fuel_type', 'mpg', 'transmission', 'drivetrain']]
df.head()

,vin,year,make,model,trim,price,location,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box 4WD,"$25,699","Littleton, CO","76,799 miles",Exterior: Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,"$10,250","Austin, TX","114,701 miles",Exterior: Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT 4WD,"$22,988","Seekonk, MA","141,184 miles",Exterior: Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,"$8,999","San Diego, CA","108,333 miles",Exterior: Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box 4WD,"$43,990$42,772","Milwaukee, WI","48,717 miles",Exterior: Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD

In [71]:
df['trim'] = df['trim'].str.replace('4WD', '')
df['trim'] = df['trim'].str.replace('AWD', '')
df['trim'] = df['trim'].str.replace('FWD', '')
df['trim'] = df['trim'].str.replace('RWD', '')
df['trim'] = df['trim'].str.replace('2WD', '')
df['trim'] = df['trim'].str.replace('Automatic', '')
df['trim'] = df['trim'].str.replace('Auto', '')
df['trim'] = df['trim'].str.replace('Manual', '')
df['trim'] = df['trim'].str.replace('CVT', '')
df.head()

,vin,year,make,model,trim,price,location,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,"$25,699","Littleton, CO","76,799 miles",Exterior: Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,"$10,250","Austin, TX","114,701 miles",Exterior: Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,"$22,988","Seekonk, MA","141,184 miles",Exterior: Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,"$8,999","San Diego, CA","108,333 miles",Exterior: Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,"$43,990$42,772","Milwaukee, WI","48,717 miles",Exterior: Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD

In [72]:
new_cols = df['price'].str.split(pat='$', n=2, expand=True)
df['price'] = new_cols[1]

df['price'] = df['price'].str.replace(',', '')
df.head()

,vin,year,make,model,trim,price,location,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,"Littleton, CO","76,799 miles",Exterior: Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,"Austin, TX","114,701 miles",Exterior: Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,"Seekonk, MA","141,184 miles",Exterior: Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,"San Diego, CA","108,333 miles",Exterior: Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,"Milwaukee, WI","48,717 miles",Exterior: Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD

In [73]:
new_cols = df['location'].str.split(pat=',', n=2, expand=True)
df['city'] = new_cols[0]
df['state'] = new_cols[1]
df.drop(['location'], axis=1, inplace=True)
df.head()

,vin,year,make,model,trim,price,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,"76,799 miles",Exterior: Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,"114,701 miles",Exterior: Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,"141,184 miles",Exterior: Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,"108,333 miles",Exterior: Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,"48,717 miles",Exterior: Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Milwaukee,WI

In [74]:
df['mileage'] = df['mileage'].str.replace(',', '')
df['mileage'] = df['mileage'].str.replace('miles', '')
df.head()

,vin,year,make,model,trim,price,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Exterior: Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Exterior: Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Exterior: Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Exterior: Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Exterior: Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Milwaukee,WI

In [75]:
df['exterior_color'] = df['exterior_color'].str.replace('Exterior: ', '')
df.head()

,vin,year,make,model,trim,price,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Oxford White,Interior: Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Super Black,Interior: Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Agate Black Metallic,Interior: Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Silver,Interior: Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Iconic Silver Metallic,Interior: Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Milwaukee,WI

In [76]:
df['interior_color'] = df['interior_color'].str.replace('Interior: ', '')
df.head()

,vin,year,make,model,trim,price,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Oxford White,Dark Earth Gray,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Super Black,Charcoal,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Agate Black Metallic,Ebony,Fuel Type: Gas,20 city / 27 highway,Automatic Transmission,4WD,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Silver,Black,Fuel Type: Gas,27 city / 38 highway,Automatic Transmission,FWD,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Iconic Silver Metallic,Black,Fuel Type: Gas,18 city / 23 highway,Automatic Transmission,4WD,Milwaukee,WI

In [77]:
df['fuel_type'] = df['fuel_type'].str.replace('Fuel Type: ', '')
df.head()

,vin,year,make,model,trim,price,mileage,exterior_color,interior_color,fuel_type,mpg,transmission,drivetrain,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Oxford White,Dark Earth Gray,Gas,18 city / 23 highway,Automatic Transmission,4WD,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Super Black,Charcoal,Gas,27 city / 38 highway,Automatic Transmission,FWD,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Agate Black Metallic,Ebony,Gas,20 city / 27 highway,Automatic Transmission,4WD,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Silver,Black,Gas,27 city / 38 highway,Automatic Transmission,FWD,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Iconic Silver Metallic,Black,Gas,18 city / 23 highway,Automatic Transmission,4WD,Milwaukee,WI

In [78]:
new_cols = df['mpg'].str.split(pat=' ', n=5, expand=True)
df['city_mpg'] = new_cols[1]
df['hwy_mpg'] = new_cols[4]
df.drop(['mpg'], axis=1, inplace=True)

df = df[['vin', 'year', 'make', 'model', 'trim', 'price', 'mileage', 'transmission', 'drivetrain', 'fuel_type', 'city_mpg', 'hwy_mpg', 'exterior_color', 'interior_color', 'city', 'state']]
df.head()

,vin,year,make,model,trim,price,mileage,transmission,drivetrain,fuel_type,city_mpg,hwy_mpg,exterior_color,interior_color,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Automatic Transmission,4WD,Gas,18,23,Oxford White,Dark Earth Gray,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Automatic Transmission,FWD,Gas,27,38,Super Black,Charcoal,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Automatic Transmission,4WD,Gas,20,27,Agate Black Metallic,Ebony,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Automatic Transmission,FWD,Gas,27,38,Silver,Black,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Automatic Transmission,4WD,Gas,18,23,Iconic Silver Metallic,Black,Milwaukee,WI

In [79]:
df['transmission'] = df['transmission'].str.replace(' Transmission', '')
df.head()

,vin,year,make,model,trim,price,mileage,transmission,drivetrain,fuel_type,city_mpg,hwy_mpg,exterior_color,interior_color,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Automatic,4WD,Gas,18,23,Oxford White,Dark Earth Gray,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Automatic,FWD,Gas,27,38,Super Black,Charcoal,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Automatic,4WD,Gas,20,27,Agate Black Metallic,Ebony,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Automatic,FWD,Gas,27,38,Silver,Black,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Automatic,4WD,Gas,18,23,Iconic Silver Metallic,Black,Milwaukee,WI

In [80]:
df['vin'] = df['vin'].str.strip()
df['year'] = df['year'].str.strip()
df['make'] = df['make'].str.strip()
df['model'] = df['model'].str.strip()
df['transmission'] = df['transmission'].str.strip()
df['drivetrain'] = df['drivetrain'].str.strip()
df['fuel_type'] = df['fuel_type'].str.strip()
df['exterior_color'] = df['exterior_color'].str.strip()
df['interior_color'] = df['interior_color'].str.strip()
df.head()

,vin,year,make,model,trim,price,mileage,transmission,drivetrain,fuel_type,city_mpg,hwy_mpg,exterior_color,interior_color,city,state
0,1FTEW1EP5LKF18954,2020,Ford,F-150,XL SuperCrew 5.5' Box,25699,76799,Automatic,4WD,Gas,18,23,Oxford White,Dark Earth Gray,Littleton,CO
1,1N4AL3AP4FC588068,2015,Nissan,Altima,2.5 S,10250,114701,Automatic,FWD,Gas,27,38,Super Black,Charcoal,Austin,TX
2,1FMSK8DH6LGB88354,2020,Ford,Explorer,XLT,22988,141184,Automatic,4WD,Gas,20,27,Agate Black Metallic,Ebony,Seekonk,MA
3,1N4AL3AP7FC185069,2015,Nissan,Altima,2.5 S,8999,108333,Automatic,FWD,Gas,27,38,Silver,Black,San Diego,CA
4,1FTEW1EP8LKF49809,2020,Ford,F-150,Lariat SuperCrew 5.5' Box,43990,48717,Automatic,4WD,Gas,18,23,Iconic Silver Metallic,Black,Milwaukee,WI

In [81]:
df.reset_index(drop=True, inplace=True)

In [82]:
df.dropna(subset=['city_mpg'], inplace=True)
df = df[df['city_mpg'] != 'N/A']

In [83]:
df['year'] = df['year'].astype(int)
df['price'] = df['price'].astype(int)
df['mileage'] = df['mileage'].astype(int)
df['city_mpg'] = df['city_mpg'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24558 entries, 0 to 25698
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   vin             24558 non-null  object
 1   year            24558 non-null  int32
 2   make            24558 non-null  object
 3   model           24558 non-null  object
 4   trim            24558 non-null  object
 5   price           24558 non-null  int32
 6   mileage         24558 non-null  int32
 7   transmission    24558 non-null  object
 8   drivetrain      24558 non-null  object
 9   fuel_type       24558 non-null  object
 10  city_mpg        24558 non-null  int32
 11  hwy_mpg         23921 non-null  object
 12  exterior_color  24558 non-null  object
 13  interior_color  24558 non-null  object
 14  city            24558 non-null  object
 15  state           23907 non-null  object
dtypes: int32(4), object(12)
memory usage: 2.8+ MB

In [85]:
df.to_parquet(r'C:\Users\Chase\OneDrive\Documents\datascienceclubuvu.github.io\tutorials\Pandas\Exercise Files\clean_listings.parquet', compression='snappy', engine='pyarrow')